<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;

class ConceptsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('concepts')->delete();
        
        \DB::table('concepts')->insert(array (
            0 => 
            array (
                'id' => 4,
                'code' => 'D-003',
                'name' => 'INFONAVIT',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 7,
                'observation' => 'Deducción INFONAVIT',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 16:06:38',
                'updated_at' => '2021-01-20 16:06:38',
            ),
            1 => 
            array (
                'id' => 6,
                'code' => 'PR-001',
                'name' => 'Aguinaldo',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 2,
                'observation' => 'Concepto del aguinaldo correspondiente a contrataciones eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 17:30:43',
                'updated_at' => '2021-01-20 17:30:43',
            ),
            2 => 
            array (
                'id' => 7,
                'code' => 'PR-002',
                'name' => 'Vacaciones',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 8,
                'observation' => 'Calculo de vacaciones para eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 17:36:32',
                'updated_at' => '2021-01-20 17:36:32',
            ),
            3 => 
            array (
                'id' => 8,
                'code' => 'PR-003',
                'name' => 'Prima Vacacional',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 4,
                'observation' => 'Prima vacacional correspondiente al eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 17:40:42',
                'updated_at' => '2021-01-20 17:40:42',
            ),
            4 => 
            array (
                'id' => 9,
                'code' => 'PR-004',
                'name' => 'ISN',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Calculo de la provisión del impuesto sobre nómina',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 17:45:39',
                'updated_at' => '2021-01-20 17:45:39',
            ),
            5 => 
            array (
                'id' => 1,
                'code' => 'P-001',
                'name' => 'Sueldo',
                'taxable_type' => 1,
                'condition_total' => NULL,
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Sueldo correspondiente a contrataciones eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 16:00:01',
                'updated_at' => '2021-01-20 18:09:01',
            ),
            6 => 
            array (
                'id' => 10,
                'code' => 'PI-001',
                'name' => 'Fondo de Ahorro Patrón',
                'taxable_type' => 2,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 5,
                'observation' => 'Fondo de ahorro institucionales 13% del sueldo',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-21 18:52:45',
                'updated_at' => '2021-01-21 18:52:45',
            ),
            7 => 
            array (
                'id' => 12,
                'code' => 'P-003',
                'name' => 'Vales de Despensa',
                'taxable_type' => 3,
                'condition_total' => '30.00',
                'cat_yearly_variable_type_id' => 1,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 1,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Vales de despensa fijo para institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => true,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 425000,
                'is_active' => true,
                'created_at' => '2021-01-21 19:00:50',
                'updated_at' => '2021-01-21 19:00:50',
            ),
            8 => 
            array (
                'id' => 3,
                'code' => 'D-002',
                'name' => 'ISR',
                'taxable_type' => NULL,
                'condition_total' => NULL,
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Concepto correspondiente a la deducción del ISR',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 16:00:01',
                'updated_at' => '2021-01-21 19:01:33',
            ),
            9 => 
            array (
                'id' => 13,
                'code' => 'DI-001',
                'name' => 'Fondo de Ahorro',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 5,
                'observation' => 'Deducción del fondo de ahorro',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-21 19:12:46',
                'updated_at' => '2021-01-21 19:12:46',
            ),
            10 => 
            array (
                'id' => 14,
                'code' => 'DI-002',
                'name' => 'Fondo de Ahorro Patrón',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 5,
                'observation' => 'DEDUCCIÓN del Fondo de Ahorro Patronal',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-21 19:14:08',
                'updated_at' => '2021-01-21 19:14:08',
            ),
            11 => 
            array (
                'id' => 15,
                'code' => 'PRI-001',
                'name' => 'Aguinaldo',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 8,
                'observation' => 'Concepto del aguinaldo para contrataciones Institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-21 19:46:55',
                'updated_at' => '2021-01-21 19:46:55',
            ),
            12 => 
            array (
                'id' => 16,
                'code' => 'PRI-002',
                'name' => 'Vacaciones',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Vacaciones para contrataciones institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-22 15:47:01',
                'updated_at' => '2021-01-22 15:47:01',
            ),
            13 => 
            array (
                'id' => 17,
                'code' => 'PRI-003',
                'name' => 'Prima Vacacional',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Prima vacacional para contrataciones institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-22 16:01:05',
                'updated_at' => '2021-01-22 16:01:05',
            ),
            14 => 
            array (
                'id' => 18,
                'code' => 'PRI-004',
                'name' => 'Gratificación Anual',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Gratificación Anual institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-22 16:13:59',
                'updated_at' => '2021-01-22 16:13:59',
            ),
            15 => 
            array (
                'id' => 2,
                'code' => 'D-001',
                'name' => 'IMSS',
                'taxable_type' => NULL,
                'condition_total' => NULL,
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Concepto correspondiente a la deducción del IMSS',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-20 16:00:01',
                'updated_at' => '2021-01-26 20:16:00',
            ),
            16 => 
            array (
                'id' => 19,
                'code' => 'PRI-005',
                'name' => 'ISR/Grat. Anual',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 3,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 7,
                'observation' => 'Provisión del ISR correspondiente a la Grat. Anual',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-22 16:23:20',
                'updated_at' => '2021-01-26 21:15:37',
            ),
            17 => 
            array (
                'id' => 11,
                'code' => 'PI-002',
                'name' => 'Compensación Garantizada',
                'taxable_type' => 1,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Compensación Garantizada Institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-21 18:56:48',
                'updated_at' => '2021-01-26 21:17:31',
            ),
            18 => 
            array (
                'id' => 22,
                'code' => 'DI-003',
                'name' => 'IMSS',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 4,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 4,
                'observation' => 'Deducción institucional del IMSS no impresa en nómina absuelta completamente por el patron',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => false,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-26 21:22:21',
                'updated_at' => '2021-01-26 21:22:21',
            ),
            19 => 
            array (
                'id' => 23,
                'code' => 'PE-001',
                'name' => 'Gratificación Anual',
                'taxable_type' => 1,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Esto es una gratificacion para contrataciones eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-30 00:13:11',
                'updated_at' => '2021-01-30 00:13:11',
            ),
            20 => 
            array (
                'id' => 24,
                'code' => 'DE-001',
                'name' => 'ISR',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 3,
                'observation' => 'Concepto de deduccion de isr para nóminas extraordinarias',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-30 00:15:05',
                'updated_at' => '2021-01-30 00:15:05',
            ),
            21 => 
            array (
                'id' => 25,
                'code' => 'PE-002',
                'name' => 'Gratificación Anual',
                'taxable_type' => 1,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 2,
                'observation' => 'Gratificación anual correspondiente a contrataciones institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-01-30 00:56:26',
                'updated_at' => '2021-01-30 00:56:26',
            ),
            22 => 
            array (
                'id' => 26,
                'code' => 'PX-003',
                'name' => 'Aguinaldo',
                'taxable_type' => 3,
                'condition_total' => '30.00',
                'cat_yearly_variable_type_id' => 1,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 2,
                'observation' => 'Percepción extraordinaria del aguinaldo para contrataciones Eventuales.',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-02-02 19:40:28',
                'updated_at' => '2021-02-02 19:40:28',
            ),
            23 => 
            array (
                'id' => 27,
                'code' => 'PX-004',
                'name' => 'Vacaciones',
                'taxable_type' => 1,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 3,
                'observation' => 'Percepción de vacaciones eventuales extraordinario',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-02-02 19:45:23',
                'updated_at' => '2021-02-02 19:45:23',
            ),
            24 => 
            array (
                'id' => 28,
                'code' => 'PX-005',
                'name' => 'Prima Vacacional',
                'taxable_type' => 3,
                'condition_total' => '15.00',
                'cat_yearly_variable_type_id' => 1,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 1,
                'observation' => 'Prima vacacional al 25% de las vacaciones, para contrataciones eventuales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-02-02 19:49:26',
                'updated_at' => '2021-02-02 19:49:26',
            ),
            25 => 
            array (
                'id' => 29,
                'code' => 'DX-001',
                'name' => 'ISR Finiquito',
                'taxable_type' => NULL,
                'condition_total' => '0.00',
                'cat_yearly_variable_type_id' => NULL,
                'cat_concept_type_id' => 2,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 7,
                'observation' => 'Deducción del ISR para finiquitos',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-02-02 19:51:09',
                'updated_at' => '2021-02-02 19:51:09',
            ),
            26 => 
            array (
                'id' => 30,
                'code' => 'PX-006',
                'name' => 'Aguinaldo',
                'taxable_type' => 3,
                'condition_total' => '30.00',
                'cat_yearly_variable_type_id' => 1,
                'cat_concept_type_id' => 1,
                'cat_concept_calculation_type_id' => 2,
                'cat_periodicity_type_id' => 10,
                'extraordinary_date' => NULL,
                'cat_sat_concept_id' => 2,
                'observation' => 'Percepción extraordinaria de cálculo de aguinaldo para contrataciones Institucionales',
                'has_validity' => false,
                'is_pantry_voucher' => false,
                'validity_start_date' => NULL,
                'validity_end_date' => NULL,
                'is_global_automatic' => false,
                'is_settlement_automatic' => false,
                'should_print' => true,
                'fixed_amount' => 0,
                'is_active' => true,
                'created_at' => '2021-02-02 22:09:16',
                'updated_at' => '2021-02-02 22:09:16',
            ),
        ));
        
        \DB::statement('ALTER SEQUENCE public.concepts_id_seq RESTART WITH 31');
    }
}