export default function () {
  return {
    generic: [{ id: 1, name: 'Opción 1' }, { id: 2, name: 'Opción 2' }],
    profiles: [],
    contracts: [],
    hiring_memos: [],
    payrolls: [],
    genders: [],
    countries: [],
    cat_bank_accounts: [],
    incident_types: [],
    banks: [],
    bank_account_types: [],
    states: [],
    marital_statuses: [],
    education_levels: [],
    education_statuses: [],
    documents: [],
    concept_imss_deduction: [],
    rules_imss_deduction: [],
    units: [],
    tabulators: [],
    sat_grouping_keys: [],
    concept_types: [],
    inability_types: [],
    concept_calculation_types: [],
    core_expression_types: [],
    concept_periodicity_types: [],
    cat_yearly_variable_type: [],
    cat_modules: [],
    cat_sat_concepts: [],
    cat_specific_budget_items: [],
    cat_type_data: [],
    cat_custom_fields: [],
    employment_types: [],
    clients: [],
    projects: [],
    employee: [],
    hiring_memo: [],
    payment_status: [],
    employment_locations: [],
    off_work_reasons: [],
    months: [],
    time_zones: [],
    cat_days: [],
    years: ['2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030']
  }
}
